services:
  web:
   build: . 
   ports:
    - "5000:5000"
    - "5678:5678"
   volumes:
    - .:/app
   command: ["sh", "-c", "pip install /tmp/deubugpy -t /tmp && python /tmp/debugpy --wait-for-clien --listen 0.0.0.0:5678 -m flask run --no-debugger --no-reload --host 0.0.0.0 --port 50000"]
