IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Activities')
BEGIN
    CREATE TABLE Activities (
        ActivityID INT IDENTITY(1,1) PRIMARY KEY,
        ActivityDescription NVARCHAR(100) NOT NULL UNIQUE
    );
END
GO