name: Notify Teams on Pull Request Events

on:
  pull_request:
    types:
      - opened  # Trigger when a PR is created
      - closed  # Trigger when a PR is merged or closed

jobs:
  notify-teams:
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Microsoft Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}  # Secure webhook URL
        run: |
          if [ "${{ github.event.action }}" == "opened" ]; then
            curl -H "Content-Type: application/json" -d '{
              "text": "🚀 **New Pull Request Created!**\n\n
              **Repository:** `${{ github.repository }}`\n
              **PR Title:** `${{ github.event.pull_request.title }}`\n
              **Created by:** `${{ github.actor }}`\n
              🔗 [View PR](${{ github.event.pull_request.html_url }})"
            }' "$TEAMS_WEBHOOK_URL"
          elif [ "${{ github.event.pull_request.merged }}" == "true" ]; then
            curl -H "Content-Type: application/json" -d '{
              "text": "✅ **Pull Request Merged!**\n\n
              **Repository:** `${{ github.repository }}`\n
              **PR Title:** `${{ github.event.pull_request.title }}`\n
              **Merged by:** `${{ github.actor }}`\n
              🔗 [View PR](${{ github.event.pull_request.html_url }})"
            }' "$TEAMS_WEBHOOK_URL"
          fi
