name: Notify Teams on Merge

on:
  pull_request:
    types:
      - closed  # Runs only when a PR is merged or closed

jobs:
  notify-teams:
    if: github.event.pull_request.merged == true  # Run only if PR is merged
    runs-on: ubuntu-latest

    steps:
      - name: Send notification to Microsoft Teams
        env:
          TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}  # Secure webhook URL
        run: |
          curl -H "Content-Type: application/json" -d '{
            "text": "✅ **Pull Request Merged!**\n\n
            **Repository:** `${{ github.repository }}`\n
            **PR Title:** `${{ github.event.pull_request.title }}`\n
            **Merged by:** `${{ github.actor }}`\n
            🔗 [View PR](${{ github.event.pull_request.html_url }})"
          }' "$TEAMS_WEBHOOK_URL"
